### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by pcrxn** [stothard-group/proksee-batch#96]
Hello! When running this program on my own genomes, I receive a `TypeError` from the `remove_covered_features.py` script (see Error log).

<details>

<summary>Error log</summary>

```
$ proksee-batch     --input proksee/bacannot/assembly/input/     --output proksee/bacannot/assembly/output/
Traceback (most recent call last):
  File "/home/liam/miniconda3/envs/proksee/bin/proksee-batch", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/liam/miniconda3/envs/proksee/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liam/miniconda3/envs/proksee/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/liam/miniconda3/envs/proksee/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liam/miniconda3/envs/proksee/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/proksee-batch/src/proksee_batch/__main__.py", line 276, in main
    add_gff_features_and_tracks(
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/proksee-batch/src/proksee_batch/parse_additional_features.py", line 684, in add_gff_features_and_tracks
    gff_features, gff_tracks = parse_gff_files(gff_files)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/proksee-batch/src/proksee_batch/parse_additional_features.py", line 626, in parse_gff_files
    remove_covered_features(
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/proksee-batch/src/proksee_batch/remove_covered_features.py", line 36, in remove_covered_features
    if other_score > score:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'float'
```
</details>

I added a few lines of code between Lines 29 and 30 in `remove_covered_features.py` to debug this error (see Code for debugging).

<details>

<summary>Code for debugging</summary>

```python
    # Iterate through each feature
    for i, (start, end, score) in enumerate(features):
        # Check for any other feature that covers this feature
        for j, (other_start, other_end, other_score) in enumerate(features):
            if i != j:
                #------- Degugging begin -------#
                print(other_score)
                print(f"other_score is type {type(other_score)}")
                print(score)
                print(f"score is type {type(score)}")
                #------- Degugging end -------#
                if other_score > score:
                    # Check if the other feature completely covers the current feature
                    if other_start <= start and other_end >= end:
                        is_not_covered[i] = False
                        break
```

</details>

Running the program again with this debugging enabled produces verbose output indicating that an encountered value of other_score is of type string (see Debug error log).

<details>

<summary>Debug error log</summary>

```
$ proksee-batch     --input proksee/bacannot/assembly/input/     --output proksee/bacannot/assembly/output/
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
0.0
other_score is type <class 'float'>
0.0
score is type <class 'float'>
140.1
other_score is type <class 'str'>
0.0
score is type <class 'float'>
Traceback (most recent call last):
  File "/home/liam/miniconda3/envs/proksee/bin/proksee-batch", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/liam/miniconda3/envs/proksee/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liam/miniconda3/envs/proksee/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/liam/miniconda3/envs/proksee/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liam/miniconda3/envs/proksee/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/proksee-batch/src/proksee_batch/__main__.py", line 276, in main
    add_gff_features_and_tracks(
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/proksee-batch/src/proksee_batch/parse_additional_features.py", line 684, in add_gff_features_and_tracks
    gff_features, gff_tracks = parse_gff_files(gff_files)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/proksee-batch/src/proksee_batch/parse_additional_features.py", line 626, in parse_gff_files
    remove_covered_features(
  File "/media/liam/Cerulean/projects/PRJ-LPB-00017/bin/proksee-batch/src/proksee_batch/remove_covered_features.py", line 36, in remove_covered_features
    if other_score > score:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'float'
```

</details>

However, simply adding `other_score = float(other_score)` in the same area of code as the debug chunk results in another error caused by an encountered value of **score** being of type string, too. So, to prevent this error from occurring for either variable, I added the following between Lines 29 and 30 in `remove_covered_features.py` (see Fix).

<details>

<summary>Fix</summary>

```python
                score = float(score)
                other_score = float(other_score)
```

</details>

After this, the program ran without any issues on my own dataset and the test dataset. Let me know if you'd like me to open a PR!

## Versions

os=Linux Mint 21.2
python=3.11
proksee-batch=0.6.4

**Comment by laelbarlow** [comment]
Hi @pcrxn ,

Thank you very much for reporting this issue.

Your modification clearly fixes the problem.

In anticipation of potential cases where "scores" may not be directly converted to floats here, I've added the type conversion to the function for parsing GFF features and added type validation to the function for comparing features and their scores. See this commit: https://github.com/stothard-group/proksee-batch/commit/f2da5c897d0a309840cf1048b1d3f7ab1be5fabe. The patched code is available in proksee-batch 0.6.5 on PyPI.
